### ISSUE TITLE
Number GUI not popping up

### ISSUE THREAD

**Issue by caraujo777** [madelinegr/titanic_escape_room#4]
The code for this issue is in the branch door_key in the file doorkey.unity

**Description:** The C# code in the **Door Key** script should make a number pad GUI should pop up when the user (first person controller) comes in contact with the box collider associated with the **Key** game object, however, even when the user is near the **Key** game object / moves past the **Key** game object the GUI doesn’t appear. The code for this is in the **door_open** branch.

**Comment by AJPana** [comment]
we can’t find door_key branch that issues mention.
![image (17)](https://user-images.githubusercontent.com/2421826/67718990-8e573000-f996-11e9-952b-c308514b4aaa.png)

Also, we can’t find the gui/canvas prefab on open_Door branch, could you give us mor info about it?
