### ISSUE TITLE
Smooth transportation in bedroom

### ISSUE THREAD

**Issue by caraujo777** [madelinegr/titanic_escape_room#6]
Code is in master branch in titanicroom.unity

The size of the main bedroom area in "titanicroom" the user can walk around is constrained by the area user set using the controllers. However, some objects are still out of reach from the user hands, as the image below shows:

<img width="433" alt="Screen Shot 2019-10-15 at 6 48 07 PM" src="https://user-images.githubusercontent.com/33438547/66875457-5acedb80-ef7c-11e9-96d6-19e88fea3bc5.png">

We wanted [this](https://www.youtube.com/watch?v=DY-ipFc8uSQ) kind of teleportation interaction in titanicroom.unity:

**Comment by madelinegr** [comment]
Add specifics of how user interaction should work
